language: python
python:
  - "2.7"
  - "3.6"
dist: xenial
branches:
  only:
    - master
os:
  - linux
#  - osx
sudo: false
before_install:
  - sudo apt-get install -y libnetcdf-dev
  - pip install flake8
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
  - make install
  - make start
  - sleep 2
#  # Prepare env with Python version
#  - conda create -n raven python=$TRAVIS_PYTHON_VERSION
#  # Update now the env with our environment
#  - conda env update -f environment.yml
#  - source activate raven
#  # Packages for testing
#  - conda install pytest flake8
#  # Install Emu WPS
#  - python setup.py install
#before_script:
#  # Start WPS service on port 5000 on 0.0.0.0
#  - raven start --daemon --bind-host 0.0.0.0 --port 5000
#  - sleep 2
script:
  - make test
  - flake8
