language: generic
matrix:
  fast_finish: true
  include:
    - os: osx
#      python: "2.7"
#    - os: osx
#      python: "3.6"
    - os: linux
      dist: xenial
      python: "2.7"
    - os: linux
      dist: xenial
      python: "3.6"
branches:
  only:
    - master
sudo: false
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libnetcdf-dev; else brew install netcdf; fi
  - pip install flake8
install:
  - make install
  - make start
  - sleep 2
#  # Prepare env with Python version
#  - conda create -n raven python=$TRAVIS_PYTHON_VERSION
#  # Update now the env with our environment
#  - conda env update -f environment.yml
#  - source activate raven
#  # Packages for testing
#  - conda install pytest flake8
#  # Install Emu WPS
#  - python setup.py install
before_script:
  # Start WPS service on port 5000 on 0.0.0.0
  - raven start --daemon --bind-host 0.0.0.0 --port 5000
  - sleep 2
script:
  - make test
#  - flake8
