language: generic

dist: xenial

jobs:
  fast_finish: true
  include:
    - os: osx
      python: "3.5"
      name: "macOS (Python3.5)"
      addons:
            homebrew:
                packages:
                    - netcdf
                update: true
      env:
            - CONDA_FN="Miniconda3-latest-MacOSX-x86_64.sh"
    - os: linux
      name: "Linux (Python3.6 + pep8)"
      dist: xenial
      python: "3.6"
      addons:
            apt:
                packages:
                    - libnetcdf-dev
      env:
            - CONDA_FN="Miniconda3-latest-Linux-x86_64.sh"
            - PEP8=true
    - os: linux
      name: "Linux (Python3.7 + docs)"
      python: "3.7"
      dist: xenial
      addons:
            apt:
                packages:
                    - libnetcdf-dev
      env:
            - CONDA_FN="Miniconda3-latest-Linux-x86_64.sh"
            - DOCS=true
    -   os: linux
        name: "Linux (Python3.8 + notebooks)"
        python: "3.8"
        dist: xenial
        addons:
            apt:
                packages:
                    - libnetcdf-dev
        env:
            - CONDA_FN="Miniconda3-latest-Linux-x86_64.sh"
            - NOTEBOOKS=true
  allow_failures:
    - env:
        - CONDA_FN="Miniconda3-latest-Linux-x86_64.sh"
        - NOTEBOOKS=true

branches:
  only:
    - master

install:
  - make bootstrap
  # Useful for debugging any issues with conda
  - /home/travis/miniconda3/bin/conda info -a
  - /home/travis/miniconda3/bin/conda run -n raven make install
#  - sleep 2
#  # Prepare env with Python version
#  - conda create -n raven python=$TRAVIS_PYTHON_VERSION
#  # Update now the env with our environment
#  - conda env update -f environment.yml
#  - source activate raven
#  # Packages for testing
#  - conda install pytest flake8
#  # Install Emu WPS
#  - python setup.py install

before_script:
#  # Start WPS service on port 5000 on 0.0.0.0
#  - raven start --daemon --bind-host 0.0.0.0 --port 5000
  - /home/travis/miniconda3/bin/conda run -n raven make start

script:
  - /home/travis/miniconda3/bin/conda run -n raven make test
  - if [[ $NOTEBOOKS = true ]]; then /home/travis/miniconda3/bin/conda run -n raven make test-notebooks; fi
  - if [[ $DOCS = true ]]; then /home/travis/miniconda3/bin/conda run -n raven make docs; fi
  - if [[ $PEP8 = true ]]; then /home/travis/miniconda3/bin/conda run -n raven make pep8; fi
