# conda env create -f environment.yml
name: birdy
channels:
  - birdhouse
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - xarray
  - numpy
  - netcdf4
  - pydap
  - cartopy
  - rioxarray
  - descartes
  - xclim
  # to edit .ipynb
  - jupyter
  # to be launched by image jupyterhub/jupyterhub
  - notebook
  # for pip packages
  - pip
  - nc-time-axis
  - ipyleaflet
  - pip:
    # visual debugger for Jupyter Notebook, not working with JupyterLab at this moment
    - owslib<0.22
    - pixiedust
    - birdhouse-birdy
    - ravenpy
