# conda env create -f environment-docs.yml
name: raven-docs
channels:
- conda-forge
- defaults
dependencies:
- python>=3.6
- pywps
- sphinx
- nbsphinx
- ipython
- xskillscore
- numpy
- sphinx_rtd_theme
#- xclim
#- rioxarray
#- pip
#- pip:
#  - ravenpy
