# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9
  - pywps ==4.5.1
  - sphinx
  - ipython
  - ipywidgets
  - nbsphinx
  - numpy
  - pandas <2.0  # Pinned for xarray<=2023.3.0 compatibility.
  - pip
  - pypandoc
  - sphinx_rtd_theme >=1.0
