# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9,<3.13
  - pywps >=4.6
  - ipyleaflet
  - ipython >=8.5.0,!=9.0.0
  - ipywidgets
  - nbsphinx >=0.9.5
  - numpy >=1.24.0
  - pandas >=2.2
  - sphinx >=7.0.0,<8.2
  - sphinx-autodoc-typehints
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton
  - sphinx-rtd-theme >=1.0
