# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - ravenpy >=0.7.7
  - python >=3.7
  - pywps ==4.5.1
  - sphinx
  - ipython
  - nbsphinx
  - numpy
  - pip
  - pypandoc
  - sphinx_rtd_theme
  - xskillscore
