name: raven
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.14
  - flit >=3.11,<4.0
  - birdy >=0.9.1
  - bump-my-version >=1.2.0
  - flake8 >=7.2.0
  - flake8-rst-docstrings >=0.3.0
  - ipykernel
  - ipywidgets
  - nbconvert >=7.13.0
  - nbval >=0.10.0
  - numpydoc >=1.8.0
  - pip >=24.2.0
  - pooch >=1.8.0
  - pre-commit >=3.6.0
  - pymetalink >=6.5.3
  - pytest >=8.0.0
  - pytest-cov >=5.0.0
  - pytest-xdist >=3.2
  - python-build >=1.2.1
  - ruff >=0.12.2
  - tox >=4.24.1
  - yamllint >=1.35.1
