name: raven
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - birdy
  - black
  - bump2version
  - cruft
  - flake8
  - ipython
  - ipywidgets
  - nbconvert
  - nbsphinx
  - nbval
  - pre-commit
  - pymetalink
  - pytest
  - pytest-dependency
  - pytest-flake8
  - pytest-notebook
  - pytest-xdist >=3.2
  - sphinx >=1.7
  - sphinx-autoapi
  - twine
  - urlpath
