# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - raven-hydro ==3.6
  - ostrich ==21.03.16
  - ravenpy >=0.11.0
  - pywps ==4.5.1
  - sphinx
  - ipython
  - ipywidgets
  - nbsphinx
  - numpy
  - pip
  - pypandoc
  - sphinx_rtd_theme >=1.0
  - xskillscore
