name: raven
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8,<3.12
  - birdy
  - black >=24.4.2
  - bump-my-version >=0.21.0
  - flake8 >=7.0
  - flake8-rst-docstrings
  - ipykernel
  - ipywidgets
  - isort >=5.13.2
  - nbconvert
  - nbval
  - pip
  - pre-commit
  - pymetalink
  - pytest
  - pytest-xdist >=3.2
  - pip
  - pip:
      - flake8-alphabetize
