name: raven
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8,<3.12
  - birdy
  - black
  - bump2version
  - flake8
  - ipykernel
  - ipywidgets
  - nbconvert
  - nbval
  - pip
  - pre-commit
  - pymetalink
  - pytest
  - pytest-dependency
  - pytest-flake8
  - pytest-notebook
  - pytest-xdist >=3.2
  - urlpath
