name: raven
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9,<3.11
  - birdy
  - black
  - bump2version
  - flake8
  - ipykernel
  - ipywidgets
  - nbconvert
  - nbsphinx
  - nbval
  - pre-commit
  - pymetalink
  - pytest
  - pytest-dependency
  - pytest-flake8
  - pytest-notebook
  - pytest-xdist >=3.2
  - sphinx >=1.7
  - sphinx-autodoc-typehints
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx_rtd_theme >=1.0
  - urlpath
