# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9,<3.11
  - pywps ==4.5.1
  - ipython
  - ipywidgets
  - nbsphinx
  - numpy
  - pandas <2.0  # Pinned for xarray<=2023.3.0 compatibility.
  - pip
  - pypandoc
  - sphinx >=1.7
  - sphinx-autodoc-typehints
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx_rtd_theme >=1.0
