# conda env create -f environment-docs.yml
name: raven-docs
channels:
- conda-forge
- defaults
dependencies:
- python>=3.6
- pywps==4.4.2
- sphinx
- nbsphinx
- ipython
- xskillscore
- numpy
- sphinx_rtd_theme
