# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - ravenpy >=0.8.0
  - pywps ==4.5.1
  - sphinx
  - ipython
  - ipywidgets
  - nbsphinx
  - numpy
  - pip
  - pypandoc
  - sphinx_rtd_theme
  - xskillscore
