# conda env create -f environment-docs.yml
name: raven-docs
channels:
- conda-forge
- defaults
dependencies:
- python >=3.7
- pywps ==4.4.5
- sphinx ==3.5.4
- nbsphinx
- ipython
- xskillscore
- numpy
- sphinx_rtd_theme
- ravenpy >=0.7.7
