# conda env create -f environment-docs.yml
name: raven-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8,<3.12
  - pywps >=4.5.1
  - ipython
  - ipywidgets
  - nbsphinx
  - numpy
  - pandas
  - sphinx >=7.0.0
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-rtd-theme >=1.0
