name: raven
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.14
  - birdy >=0.9.1
  # development
  - bump-my-version >=1.3.0
  - coverage >=7.13.0
  - cruft >=2.16.0
  - flake8 >=7.2.0
  - flake8-rst-docstrings >=0.3.0
  - flit >=3.11.0,<4.0
  - ipykernel
  - ipython >=9.0.0
  - ipywidgets
  - nbconvert >=7.13.0
  - nbsphinx >=0.9.8
  - nbval >=0.10.0
  - numpydoc >=1.8.0
  - pooch >=1.8.0
  - pymetalink >=6.5.3
  - pytest >=9.0.0
  - pytest-cov >=7.1.0
  - pytest-xdist >=3.2
  - ruff >=0.15.0
  - sphinx >=9.0.0
  - sphinx-autobuild >=2024.4.16
  - sphinx-click
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton >=0.5.2
  - tox >=4.52.0
  - tox-gh >=1.7.1
  - vulture >=2.14
  - watchdog >=6.0.0
  - yamllint >=1.35.1
