name: raven
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.14
  - flit >=3.11,<4.0
  - birdy >=0.8.6
  - black >=25.1.0
  - blackdoc >=0.3.9
  - bump-my-version >=1.2.0
  - flake8 >=7.1.1
  - flake8-rst-docstrings >=0.3.0
  - ipykernel
  - ipywidgets
  - nbconvert
  - nbval
  - numpydoc >=1.8.0
  - pip >=24.2.0
  - pooch >=1.8.0
  - pre-commit >=3.6.0
  - pytest >=8.0.0
  - pytest-cov >=5.0.0
  - pytest-xdist >=3.2
  - python-build >=1.2.1
  - ruff >=0.12.2
  - tox >=4.24.1
  - yamllint >=1.35.1
