# conda env create -f environment-docs.yml
name: raven-docs
channels:
- conda-forge
- defaults
dependencies:
- python>=3.6
- pywps
- sphinx
- nbsphinx
- ipython
#- xskillscore
#- xclim
- numpy
- sphinx_rtd_theme
#- rioxarray
#- gdal
#- pip
#- pip:
#  - ravenpy
