# conda env create -f environment-docs.yml
name: raven-docs
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- pywps>=4.2
- sphinx
- nbsphinx
- ipython
- xskillscore
- xclim==0.18
- sphinx_rtd_theme
- rioxarray
- gdal
- pip:
  - ravenpy